-- ============================================================
-- STENNA WALLPAPER PLATFORM — FULL SUPABASE SCHEMA
-- Generated by reverse-engineering backend controllers,
-- routes, admin UI modals, and the existing schema.sql.
--
-- Run this on a fresh self-hosted Supabase instance.
-- Supabase already creates the `auth` schema; all application
-- tables live in `public`.
-- ============================================================

-- ── Extensions ──────────────────────────────────────────────
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pg_trgm";   -- for fast ILIKE search


-- ════════════════════════════════════════════════════════════
-- 1. PROFILES  (public shadow of auth.users)
-- Roles: admin | customer | dealer
-- ════════════════════════════════════════════════════════════
CREATE TABLE IF NOT EXISTS public.profiles (
    id          UUID        PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    email       TEXT        UNIQUE,
    full_name   TEXT,
    avatar_url  TEXT,
    role        TEXT        NOT NULL DEFAULT 'customer'
                            CHECK (role IN ('admin', 'customer', 'dealer')),
    phone       TEXT,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
COMMENT ON TABLE public.profiles IS 'Public user profiles mirroring auth.users. Roles: admin, customer, dealer.';


-- ════════════════════════════════════════════════════════════
-- 2. CATEGORY GROUPS  (top-level taxonomy, e.g. Style, Color, Room)
-- ════════════════════════════════════════════════════════════
CREATE TABLE IF NOT EXISTS public.category_groups (
    id          UUID        PRIMARY KEY DEFAULT uuid_generate_v4(),
    name        TEXT        NOT NULL,
    slug        TEXT        UNIQUE NOT NULL,
    image_url   TEXT,
    description TEXT,
    is_active   BOOLEAN     NOT NULL DEFAULT true,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
COMMENT ON TABLE public.category_groups IS 'Top-level category taxonomy groups (e.g. Style, Color, Room Type).';


-- ════════════════════════════════════════════════════════════
-- 3. CATEGORIES  (belong to a group; e.g. "Floral" in "Style")
-- ════════════════════════════════════════════════════════════
CREATE TABLE IF NOT EXISTS public.categories (
    id          UUID        PRIMARY KEY DEFAULT uuid_generate_v4(),
    group_id    UUID        REFERENCES public.category_groups(id) ON DELETE SET NULL,
    name        TEXT        NOT NULL,
    slug        TEXT        UNIQUE NOT NULL,
    image_url   TEXT,
    description TEXT,
    is_active   BOOLEAN     NOT NULL DEFAULT true,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
COMMENT ON TABLE public.categories IS 'Sub-categories belonging to a category_group (e.g. Floral, Geometric, Bedroom).';


-- ════════════════════════════════════════════════════════════
-- 4. WALLPAPERS  (core product table)
-- Fields sourced from:
--   • wallpaperController.js  — name, slug, design_code, description,
--                               is_active, views, quantity, price
--   • WallpaperModal.jsx      — roll_width, roll_height, material, finish,
--                               washability, durability, brand, country,
--                               tagline, vibe, choose_if, ideal_for,
--                               avoid_if, swatch
--   • aiController.js         — vibe, description, choose_if, ideal_for,
--                               avoid_if (used for AI scoring)
-- ════════════════════════════════════════════════════════════
CREATE TABLE IF NOT EXISTS public.wallpapers (
    id              UUID        PRIMARY KEY DEFAULT uuid_generate_v4(),
    name            TEXT        NOT NULL,
    slug            TEXT        UNIQUE NOT NULL,
    design_code     TEXT        UNIQUE NOT NULL,

    -- Product info
    description     TEXT,
    price           NUMERIC(10, 2),
    quantity        INTEGER     NOT NULL DEFAULT 0,
    views           INTEGER     NOT NULL DEFAULT 0,
    is_active       BOOLEAN     NOT NULL DEFAULT true,

    -- Physical specifications
    roll_width      NUMERIC(6, 2),      -- in cm  (e.g. 53)
    roll_height     NUMERIC(6, 2),      -- in metres (e.g. 10)
    material        TEXT,               -- e.g. Non-woven, Vinyl
    finish          TEXT,               -- e.g. Matte, Glossy, Embossed
    washability     TEXT,               -- e.g. Washable, Scrubbable
    durability      TEXT,               -- e.g. High, Medium
    brand           TEXT,               -- e.g. Luxe Walls
    country         TEXT,               -- e.g. Italy, India

    -- Swatch thumbnail (single URL, cleaned up on wallpaper delete)
    swatch          TEXT,

    -- AI / Storytelling fields (used by OpenAI recommender & scoring engine)
    tagline         TEXT,               -- Short marketing tagline
    vibe            TEXT,               -- Mood descriptor (e.g. "calm, luxurious")
    choose_if       TEXT,               -- Guidance copy
    ideal_for       TEXT,               -- Room type hints (e.g. "bedroom, living room")
    avoid_if        TEXT,               -- Negative-score hints for AI

    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);
COMMENT ON TABLE public.wallpapers IS 'Core product table. Contains physical specs, AI storytelling fields, and inventory data.';


-- ════════════════════════════════════════════════════════════
-- 5. WALLPAPER IMAGES  (up to 6 ordered images per wallpaper)
-- ════════════════════════════════════════════════════════════
CREATE TABLE IF NOT EXISTS public.wallpaper_images (
    id              UUID        PRIMARY KEY DEFAULT uuid_generate_v4(),
    wallpaper_id    UUID        NOT NULL REFERENCES public.wallpapers(id) ON DELETE CASCADE,
    image_url       TEXT        NOT NULL,
    position        INTEGER     NOT NULL DEFAULT 0,  -- 1-based sort order
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);
COMMENT ON TABLE public.wallpaper_images IS 'Ordered image gallery for each wallpaper (max 6 images). Stored on VPS.';


-- ════════════════════════════════════════════════════════════
-- 6. WALLPAPER VIDEOS  (ordered videos per wallpaper)
-- ════════════════════════════════════════════════════════════
CREATE TABLE IF NOT EXISTS public.wallpaper_videos (
    id              UUID        PRIMARY KEY DEFAULT uuid_generate_v4(),
    wallpaper_id    UUID        NOT NULL REFERENCES public.wallpapers(id) ON DELETE CASCADE,
    video_url       TEXT        NOT NULL,
    position        INTEGER     NOT NULL DEFAULT 0,  -- 1-based sort order
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);
COMMENT ON TABLE public.wallpaper_videos IS 'Ordered video gallery for each wallpaper (e.g. sponge-wash demo). Stored on VPS.';


-- ════════════════════════════════════════════════════════════
-- 7. WALLPAPER ↔ CATEGORIES  (M:M junction)
-- ════════════════════════════════════════════════════════════
CREATE TABLE IF NOT EXISTS public.wallpaper_categories (
    wallpaper_id    UUID    NOT NULL REFERENCES public.wallpapers(id) ON DELETE CASCADE,
    category_id     UUID    NOT NULL REFERENCES public.categories(id) ON DELETE CASCADE,
    PRIMARY KEY (wallpaper_id, category_id)
);
COMMENT ON TABLE public.wallpaper_categories IS 'Many-to-many: wallpapers can belong to multiple categories.';


-- ════════════════════════════════════════════════════════════
-- 8. WALLPAPER ↔ GROUPS  (M:M junction — direct group assignment)
-- ════════════════════════════════════════════════════════════
CREATE TABLE IF NOT EXISTS public.wallpaper_groups (
    wallpaper_id    UUID    NOT NULL REFERENCES public.wallpapers(id) ON DELETE CASCADE,
    group_id        UUID    NOT NULL REFERENCES public.category_groups(id) ON DELETE CASCADE,
    PRIMARY KEY (wallpaper_id, group_id)
);
COMMENT ON TABLE public.wallpaper_groups IS 'Many-to-many: direct wallpaper-to-group assignment (collection filter).';


-- ════════════════════════════════════════════════════════════
-- 9. BOOKS  (product catalogues / sample books)
-- ════════════════════════════════════════════════════════════
CREATE TABLE IF NOT EXISTS public.books (
    id          UUID        PRIMARY KEY DEFAULT uuid_generate_v4(),
    name        TEXT        NOT NULL,
    code        TEXT        UNIQUE NOT NULL,    -- Short identifier (e.g. "LX-2024")
    description TEXT,
    image_url   TEXT,
    is_active   BOOLEAN     NOT NULL DEFAULT true,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
COMMENT ON TABLE public.books IS 'Sample books / physical catalogues. Each book groups a set of wallpapers for dealers.';


-- ════════════════════════════════════════════════════════════
-- 10. BOOK ↔ WALLPAPERS  (M:M junction)
-- ════════════════════════════════════════════════════════════
CREATE TABLE IF NOT EXISTS public.book_wallpapers (
    book_id         UUID    NOT NULL REFERENCES public.books(id) ON DELETE CASCADE,
    wallpaper_id    UUID    NOT NULL REFERENCES public.wallpapers(id) ON DELETE CASCADE,
    PRIMARY KEY (book_id, wallpaper_id)
);
COMMENT ON TABLE public.book_wallpapers IS 'Many-to-many: which wallpapers appear in which book.';


-- ════════════════════════════════════════════════════════════
-- 11. DEALERS  (B2B partners with custom auth, not Supabase auth)
-- ════════════════════════════════════════════════════════════
CREATE TABLE IF NOT EXISTS public.dealers (
    id          UUID        PRIMARY KEY DEFAULT uuid_generate_v4(),
    email       TEXT        UNIQUE NOT NULL,
    password    TEXT,                           -- bcrypt hash (custom dealer auth)
    name        TEXT        NOT NULL,
    phone       TEXT,
    address     TEXT,
    is_active   BOOLEAN     NOT NULL DEFAULT true,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
COMMENT ON TABLE public.dealers IS 'B2B dealer accounts with custom bcrypt password auth (separate from Supabase auth).';


-- ════════════════════════════════════════════════════════════
-- 12. DEALER ↔ BOOKS  (M:M junction — book access control)
-- ════════════════════════════════════════════════════════════
CREATE TABLE IF NOT EXISTS public.dealer_books (
    dealer_id   UUID    NOT NULL REFERENCES public.dealers(id) ON DELETE CASCADE,
    book_id     UUID    NOT NULL REFERENCES public.books(id) ON DELETE CASCADE,
    PRIMARY KEY (dealer_id, book_id)
);
COMMENT ON TABLE public.dealer_books IS 'Controls which books/catalogues each dealer has access to.';


-- ════════════════════════════════════════════════════════════
-- 13. LEADS  (enquiries, sample requests, appointments)
-- ════════════════════════════════════════════════════════════
CREATE TABLE IF NOT EXISTS public.leads (
    id              UUID        PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id         UUID        REFERENCES public.profiles(id) ON DELETE SET NULL,
    wallpaper_id    UUID        REFERENCES public.wallpapers(id) ON DELETE SET NULL,
    full_name       TEXT,                    -- NOTE: column is "full_name" in schema; code uses l.name
    name            TEXT,                    -- alias used by frontend (kept for compatibility)
    email           TEXT        NOT NULL,
    phone           TEXT,
    message         TEXT,
    type            TEXT        NOT NULL DEFAULT 'enquiry'
                                CHECK (type IN ('enquiry', 'sample', 'appointment')),
    status          TEXT        NOT NULL DEFAULT 'pending'
                                CHECK (status IN ('pending', 'processing', 'resolved', 'closed')),
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);
COMMENT ON TABLE public.leads IS 'Customer inbound leads: enquiries, sample requests, and appointment bookings.';


-- ════════════════════════════════════════════════════════════
-- 14. WISHLIST
-- ════════════════════════════════════════════════════════════
CREATE TABLE IF NOT EXISTS public.wishlist (
    id              UUID        PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id         UUID        NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    wallpaper_id    UUID        NOT NULL REFERENCES public.wallpapers(id) ON DELETE CASCADE,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (user_id, wallpaper_id)
);
COMMENT ON TABLE public.wishlist IS 'Per-user saved/favourited wallpapers.';


-- ════════════════════════════════════════════════════════════
-- 15. VISUALIZATIONS  (AI Room Visualizer history)
-- ════════════════════════════════════════════════════════════
CREATE TABLE IF NOT EXISTS public.visualizations (
    id                  UUID        PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id             UUID        REFERENCES public.profiles(id) ON DELETE SET NULL,
    wallpaper_id        UUID        REFERENCES public.wallpapers(id) ON DELETE SET NULL,
    room_image_url      TEXT        NOT NULL,    -- Uploaded room photo (VPS)
    generated_image_url TEXT        NOT NULL,    -- AI-generated result (VPS)
    mask_data           JSONB,                   -- Optional drawing/mask overlay
    settings            JSONB       NOT NULL DEFAULT '{}',  -- {taskId, prompt, vps_filename, …}
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);
COMMENT ON TABLE public.visualizations IS 'History of AI-generated room visualizations (KIE.AI powered). Images stored on VPS.';


-- ════════════════════════════════════════════════════════════
-- 16. ANALYTICS  (event tracking: view, share)
-- ════════════════════════════════════════════════════════════
CREATE TABLE IF NOT EXISTS public.analytics (
    id              UUID        PRIMARY KEY DEFAULT uuid_generate_v4(),
    wallpaper_id    UUID        REFERENCES public.wallpapers(id) ON DELETE CASCADE,
    event_type      TEXT        NOT NULL
                                CHECK (event_type IN ('view', 'share', 'wishlist', 'lead')),
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);
COMMENT ON TABLE public.analytics IS 'Immutable event log for wallpaper analytics (view, share). Used to derive popularity.';


-- ════════════════════════════════════════════════════════════
-- 17. STORE SETTINGS  (single-row store configuration)
-- ════════════════════════════════════════════════════════════
CREATE TABLE IF NOT EXISTS public.store_settings (
    id                      UUID        PRIMARY KEY DEFAULT uuid_generate_v4(),
    name                    TEXT,
    logo_url                TEXT,
    email                   TEXT,
    phone                   TEXT,
    whatsapp                TEXT,
    address                 TEXT,
    working_hours           TEXT,
    map_link                TEXT,
    website                 TEXT,
    currency                TEXT        NOT NULL DEFAULT 'INR',
    tax_rate                NUMERIC(5,2) NOT NULL DEFAULT 18,
    daily_ai_credit_limit   INTEGER     NOT NULL DEFAULT 100,
    facebook_url            TEXT,
    instagram_url           TEXT,
    twitter_url             TEXT,
    linkedin_url            TEXT,
    created_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at              TIMESTAMPTZ NOT NULL DEFAULT now()
);
COMMENT ON TABLE public.store_settings IS 'Singleton store configuration (branding, contact, AI credit limit, social links).';


-- ════════════════════════════════════════════════════════════
-- 18. USER API USAGE  (daily AI credit counter per user)
-- ════════════════════════════════════════════════════════════
CREATE TABLE IF NOT EXISTS public.user_api_usage (
    user_id     UUID    NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    usage_date  DATE    NOT NULL DEFAULT CURRENT_DATE,
    hits_count  INTEGER NOT NULL DEFAULT 0,
    PRIMARY KEY (user_id, usage_date)
);
COMMENT ON TABLE public.user_api_usage IS 'Tracks daily AI API hit count per user against store_settings.daily_ai_credit_limit.';


-- ════════════════════════════════════════════════════════════
-- 19. API USAGE LOGS  (detailed audit trail)
-- ════════════════════════════════════════════════════════════
CREATE TABLE IF NOT EXISTS public.api_usage_logs (
    id          UUID        PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id     UUID        REFERENCES public.profiles(id) ON DELETE CASCADE,
    endpoint    TEXT        NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
COMMENT ON TABLE public.api_usage_logs IS 'Detailed audit log of AI API calls per user and endpoint.';


-- ════════════════════════════════════════════════════════════
-- 20. WA_INVENTORY  (WhatsApp Bot — stock inventory sync)
-- Table name in supabase service is lowercase 'wa_inventory'
-- ════════════════════════════════════════════════════════════
CREATE TABLE IF NOT EXISTS public.wa_inventory (
    id          UUID        PRIMARY KEY DEFAULT uuid_generate_v4(),
    design_code TEXT        UNIQUE NOT NULL,
    quantity    INTEGER     NOT NULL DEFAULT 0,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
COMMENT ON TABLE public.wa_inventory IS 'Stock inventory synced via WhatsApp bot CSV uploads (design_code → quantity).';


-- ════════════════════════════════════════════════════════════
-- 21. WA_ENQUIRIES  (WhatsApp Bot — inbound enquiry log)
-- Statuses: Pending | Processing | Resolved
-- ════════════════════════════════════════════════════════════
CREATE TABLE IF NOT EXISTS public.wa_enquiries (
    id              UUID        PRIMARY KEY DEFAULT uuid_generate_v4(),
    name            TEXT,
    phone_number    TEXT        NOT NULL,
    design_code     TEXT        NOT NULL,
    quantity        INTEGER     NOT NULL DEFAULT 1,
    status          TEXT        NOT NULL DEFAULT 'Pending'
                                CHECK (status IN ('Pending', 'Processing', 'Resolved')),
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);
COMMENT ON TABLE public.wa_enquiries IS 'Inbound WhatsApp customer enquiries captured by the WA bot (name, phone, design code, qty).';


-- ════════════════════════════════════════════════════════════
-- AUTO-UPDATE TRIGGERS  (keep updated_at fresh)
-- ════════════════════════════════════════════════════════════
CREATE OR REPLACE FUNCTION public.update_updated_at_column()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$;

-- profiles
DROP TRIGGER IF EXISTS trg_profiles_updated_at ON public.profiles;
CREATE TRIGGER trg_profiles_updated_at
    BEFORE UPDATE ON public.profiles
    FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

-- wallpapers
DROP TRIGGER IF EXISTS trg_wallpapers_updated_at ON public.wallpapers;
CREATE TRIGGER trg_wallpapers_updated_at
    BEFORE UPDATE ON public.wallpapers
    FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

-- store_settings
DROP TRIGGER IF EXISTS trg_store_settings_updated_at ON public.store_settings;
CREATE TRIGGER trg_store_settings_updated_at
    BEFORE UPDATE ON public.store_settings
    FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

-- wa_inventory
DROP TRIGGER IF EXISTS trg_wa_inventory_updated_at ON public.wa_inventory;
CREATE TRIGGER trg_wa_inventory_updated_at
    BEFORE UPDATE ON public.wa_inventory
    FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

-- wa_enquiries
DROP TRIGGER IF EXISTS trg_wa_enquiries_updated_at ON public.wa_enquiries;
CREATE TRIGGER trg_wa_enquiries_updated_at
    BEFORE UPDATE ON public.wa_enquiries
    FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();


-- ════════════════════════════════════════════════════════════
-- INDEXES  (performance for common query patterns)
-- ════════════════════════════════════════════════════════════

-- Wallpapers: primary lookups
CREATE INDEX IF NOT EXISTS idx_wallpapers_slug           ON public.wallpapers(slug);
CREATE INDEX IF NOT EXISTS idx_wallpapers_design_code    ON public.wallpapers(design_code);
CREATE INDEX IF NOT EXISTS idx_wallpapers_is_active      ON public.wallpapers(is_active);
CREATE INDEX IF NOT EXISTS idx_wallpapers_views          ON public.wallpapers(views DESC);
CREATE INDEX IF NOT EXISTS idx_wallpapers_created_at     ON public.wallpapers(created_at DESC);

-- Full-text / ILIKE search support via trigram
CREATE INDEX IF NOT EXISTS idx_wallpapers_name_trgm      ON public.wallpapers USING gin (name gin_trgm_ops);
CREATE INDEX IF NOT EXISTS idx_wallpapers_design_trgm    ON public.wallpapers USING gin (design_code gin_trgm_ops);

-- Books
CREATE INDEX IF NOT EXISTS idx_books_code                ON public.books(code);
CREATE INDEX IF NOT EXISTS idx_books_is_active           ON public.books(is_active);

-- Categories
CREATE INDEX IF NOT EXISTS idx_categories_group_id       ON public.categories(group_id);
CREATE INDEX IF NOT EXISTS idx_categories_slug           ON public.categories(slug);

-- Junction tables
CREATE INDEX IF NOT EXISTS idx_wc_category_id            ON public.wallpaper_categories(category_id);
CREATE INDEX IF NOT EXISTS idx_wc_wallpaper_id           ON public.wallpaper_categories(wallpaper_id);
CREATE INDEX IF NOT EXISTS idx_wg_group_id               ON public.wallpaper_groups(group_id);
CREATE INDEX IF NOT EXISTS idx_bw_book_id                ON public.book_wallpapers(book_id);
CREATE INDEX IF NOT EXISTS idx_db_dealer_id              ON public.dealer_books(dealer_id);

-- Images & Videos
CREATE INDEX IF NOT EXISTS idx_wallpaper_images_wp_id    ON public.wallpaper_images(wallpaper_id);
CREATE INDEX IF NOT EXISTS idx_wallpaper_videos_wp_id    ON public.wallpaper_videos(wallpaper_id);

-- Leads
CREATE INDEX IF NOT EXISTS idx_leads_type                ON public.leads(type);
CREATE INDEX IF NOT EXISTS idx_leads_status              ON public.leads(status);
CREATE INDEX IF NOT EXISTS idx_leads_wallpaper_id        ON public.leads(wallpaper_id);
CREATE INDEX IF NOT EXISTS idx_leads_user_id             ON public.leads(user_id);
CREATE INDEX IF NOT EXISTS idx_leads_created_at          ON public.leads(created_at DESC);

-- Wishlist
CREATE INDEX IF NOT EXISTS idx_wishlist_user_id          ON public.wishlist(user_id);

-- Visualizations
CREATE INDEX IF NOT EXISTS idx_viz_user_id               ON public.visualizations(user_id);
CREATE INDEX IF NOT EXISTS idx_viz_created_at            ON public.visualizations(created_at DESC);

-- Analytics
CREATE INDEX IF NOT EXISTS idx_analytics_wallpaper_id   ON public.analytics(wallpaper_id);
CREATE INDEX IF NOT EXISTS idx_analytics_event_type     ON public.analytics(event_type);
CREATE INDEX IF NOT EXISTS idx_analytics_created_at     ON public.analytics(created_at DESC);

-- WA Inventory / Enquiries
CREATE INDEX IF NOT EXISTS idx_wa_inventory_design_code ON public.wa_inventory(design_code);
CREATE INDEX IF NOT EXISTS idx_wa_enquiries_phone       ON public.wa_enquiries(phone_number);
CREATE INDEX IF NOT EXISTS idx_wa_enquiries_status      ON public.wa_enquiries(status);
CREATE INDEX IF NOT EXISTS idx_wa_enquiries_created_at  ON public.wa_enquiries(created_at DESC);

-- API usage
CREATE INDEX IF NOT EXISTS idx_api_usage_logs_user_id   ON public.api_usage_logs(user_id);
CREATE INDEX IF NOT EXISTS idx_api_usage_logs_created   ON public.api_usage_logs(created_at DESC);


-- ════════════════════════════════════════════════════════════
-- ROW LEVEL SECURITY (RLS)
-- The Node.js backend uses the service_role key (bypasses RLS).
-- RLS below is for direct Supabase JS client calls from the
-- website frontend (anon / authenticated users).
-- ════════════════════════════════════════════════════════════

ALTER TABLE public.profiles          ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.category_groups   ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.categories        ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.wallpapers        ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.wallpaper_images  ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.wallpaper_videos  ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.wallpaper_categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.wallpaper_groups  ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.books             ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.book_wallpapers   ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.dealers           ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.dealer_books      ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.leads             ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.wishlist          ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.visualizations    ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.analytics         ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.store_settings    ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_api_usage    ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.api_usage_logs    ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.wa_inventory      ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.wa_enquiries      ENABLE ROW LEVEL SECURITY;

-- ── Public read-only data (catalogue browsing) ──────────────
CREATE POLICY "Public can view active wallpapers"
    ON public.wallpapers FOR SELECT
    USING (is_active = true);

CREATE POLICY "Public can view category groups"
    ON public.category_groups FOR SELECT
    USING (is_active = true);

CREATE POLICY "Public can view categories"
    ON public.categories FOR SELECT
    USING (is_active = true);

CREATE POLICY "Public can view wallpaper images"
    ON public.wallpaper_images FOR SELECT
    USING (true);

CREATE POLICY "Public can view wallpaper videos"
    ON public.wallpaper_videos FOR SELECT
    USING (true);

CREATE POLICY "Public can view wallpaper-category links"
    ON public.wallpaper_categories FOR SELECT
    USING (true);

CREATE POLICY "Public can view wallpaper-group links"
    ON public.wallpaper_groups FOR SELECT
    USING (true);

CREATE POLICY "Public can view active books"
    ON public.books FOR SELECT
    USING (is_active = true);

CREATE POLICY "Public can view book-wallpaper links"
    ON public.book_wallpapers FOR SELECT
    USING (true);

CREATE POLICY "Public can view store settings"
    ON public.store_settings FOR SELECT
    USING (true);

-- ── Profiles ────────────────────────────────────────────────
CREATE POLICY "Users can view own profile"
    ON public.profiles FOR SELECT
    USING (auth.uid() = id);

CREATE POLICY "Users can update own profile"
    ON public.profiles FOR UPDATE
    USING (auth.uid() = id);

-- ── Wishlist ────────────────────────────────────────────────
CREATE POLICY "Users can manage own wishlist"
    ON public.wishlist FOR ALL
    USING (auth.uid() = user_id);

-- ── Leads: anyone can insert, owner can read own ────────────
CREATE POLICY "Anyone can submit a lead"
    ON public.leads FOR INSERT
    WITH CHECK (true);

CREATE POLICY "Authenticated users can view own leads"
    ON public.leads FOR SELECT
    USING (auth.uid() = user_id);

-- ── Visualizations ──────────────────────────────────────────
CREATE POLICY "Users can manage own visualizations"
    ON public.visualizations FOR ALL
    USING (auth.uid() = user_id);

-- ── Analytics: anyone can insert events ─────────────────────
CREATE POLICY "Anyone can record analytics events"
    ON public.analytics FOR INSERT
    WITH CHECK (true);

-- ── AI Usage ────────────────────────────────────────────────
CREATE POLICY "Users can view own AI usage"
    ON public.user_api_usage FOR SELECT
    USING (auth.uid() = user_id);

-- ── Admin-only tables (access only via service_role backend) ─
-- dealers, dealer_books, wa_inventory, wa_enquiries, api_usage_logs
-- are NOT accessible directly by client-side apps (no permissive policies).
-- The Express backend uses SUPABASE_SERVICE_ROLE_KEY which bypasses RLS.


-- ════════════════════════════════════════════════════════════
-- HELPER: Auto-create profile on auth.users insert
-- (Supabase Postgres trigger — runs server-side)
-- ════════════════════════════════════════════════════════════
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER SET search_path = public
AS $$
BEGIN
    INSERT INTO public.profiles (id, email, full_name, role)
    VALUES (
        NEW.id,
        NEW.email,
        COALESCE(NEW.raw_user_meta_data->>'full_name', split_part(NEW.email, '@', 1)),
        COALESCE(NEW.raw_user_meta_data->>'role', 'customer')
    )
    ON CONFLICT (id) DO NOTHING;
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
    AFTER INSERT ON auth.users
    FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();


-- ════════════════════════════════════════════════════════════
-- SEED: Default store settings row
-- (edit values after running)
-- ════════════════════════════════════════════════════════════
INSERT INTO public.store_settings (
    name, email, phone, whatsapp, currency, tax_rate, daily_ai_credit_limit
) VALUES (
    'Stenna', 'hello@stenna.in', '+91-XXXXXXXXXX', '+91-XXXXXXXXXX', 'INR', 18, 100
)
ON CONFLICT DO NOTHING;


-- ════════════════════════════════════════════════════════════
-- END OF SCHEMA
-- ════════════════════════════════════════════════════════════
