import { useState, useEffect, useCallback } from 'react';
import api from '../utils/api';
import { Download, Search, Trash2, Calendar, CheckCircle, Clock, AlertCircle } from 'lucide-react';
import AdminLayout from '../components/AdminLayout';
import Papa from 'papaparse';
import Button from '../components/ui/Button';

const Enquiries = () => {
    const [enquiries, setEnquiries] = useState([]);
    const [loading, setLoading] = useState(true);
    
    // Filters & Pagination
    const [searchTerm, setSearchTerm] = useState('');
    const [startDate, setStartDate] = useState('');
    const [endDate, setEndDate] = useState('');
    const [page, setPage] = useState(1);
    const [limit, setLimit] = useState(50);
    const [totalCount, setTotalCount] = useState(0);

    const fetchEnquiries = useCallback(async () => {
        setLoading(true);
        try {
            let url = `/wa-enquiries?page=${page}&limit=${limit}&search=${encodeURIComponent(searchTerm)}`;
            if (startDate) url += `&startDate=${startDate}T00:00:00Z`;
            if (endDate) url += `&endDate=${endDate}T23:59:59Z`;
            
            const res = await api.get(url);
            setEnquiries(res.data.data?.data || []);
            setTotalCount(res.data.data?.count || 0);
        } catch (err) {
            console.error("Failed to fetch enquiries", err);
        } finally {
            setLoading(false);
        }
    }, [searchTerm, startDate, endDate, page, limit]);

    useEffect(() => {
        setPage(1); // Reset to page 1 on new search or filter
    }, [searchTerm, startDate, endDate]);

    useEffect(() => {
        const delayDebounceFn = setTimeout(() => {
            fetchEnquiries();
        }, 500);
        return () => clearTimeout(delayDebounceFn);
    }, [searchTerm, startDate, endDate, page, limit, fetchEnquiries]);

    const handleStatusChange = async (id, newStatus) => {
        try {
            await api.put(`/wa-enquiries/${id}/status`, { status: newStatus });
            setEnquiries(enquiries.map(enq => 
                enq.id === id ? { ...enq, status: newStatus } : enq
            ));
        } catch (err) {
            alert('Failed to update status.');
        }
    };

    const handleDelete = async (id) => {
        if (!window.confirm("Are you sure you want to delete this enquiry?")) return;
        try {
            await api.delete(`/wa-enquiries/${id}`);
            fetchEnquiries();
        } catch (err) {
            alert('Failed to delete enquiry.');
        }
    };

    const downloadCSV = () => {
        if (enquiries.length === 0) return;
        const data = enquiries.map((item, index) => ({
            'S.No': index + 1,
            'Name': item.name || 'N/A',
            'Phone Number': item.phone_number,
            'Design Code': item.design_code,
            'Quantity': item.quantity,
            'Status': item.status,
            'Date Ordered': new Date(item.created_at).toLocaleDateString(),
            'Time Ordered': new Date(item.created_at).toLocaleTimeString()
        }));
        const csv = Papa.unparse(data);
        const blob = new Blob([csv], { type: 'text/csv;charset=utf-8;' });
        const link = document.createElement('a');
        const url = URL.createObjectURL(blob);
        link.setAttribute('href', url);
        link.setAttribute('download', 'wa_enquiries_export.csv');
        link.style.visibility = 'hidden';
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
    };

    const getStatusColor = (status) => {
        switch (status) {
            case 'Resolved': return '#22c55e'; // Green
            case 'Processing': return '#3b82f6'; // Blue
            default: return '#f59e0b'; // Orange for Pending
        }
    };

    return (
        <AdminLayout>
            <div className="page-header">
                <div className="header-content">
                    <h1>Enquiry Management</h1>
                    <p>Manage product enquiries generated by your WhatsApp Chatbot</p>
                </div>
            </div>

            <div style={{ padding: '2rem' }}>
                <section style={{ background: 'var(--bg-card)', padding: '2rem', borderRadius: '1rem', border: '1px solid var(--border-color)' }}>
                    {/* Header Row: Title and Search/Export tools */}
                    <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '1.5rem', flexWrap: 'wrap', gap: '1rem' }}>
                        <h3 style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', margin: 0, color: 'var(--text-primary)' }}>
                            Enquiries Log
                        </h3>
                        <div style={{ display: 'flex', gap: '0.5rem', alignItems: 'center', flexWrap: 'wrap' }}>
                            <div style={{ position: 'relative' }}>
                                <Search size={16} style={{ position: 'absolute', left: '0.75rem', top: '50%', transform: 'translateY(-50%)', color: 'var(--text-secondary)' }} />
                                <input 
                                    type="text" 
                                    placeholder="Search name, phone, code..." 
                                    value={searchTerm}
                                    onChange={(e) => setSearchTerm(e.target.value)}
                                    style={{ padding: '0.5rem 1rem 0.5rem 2.25rem', border: '1px solid var(--border-color)', borderRadius: '0.5rem', background: 'var(--bg-hover)', color: 'var(--text-primary)', width: '250px' }}
                                />
                            </div>
                            <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', background: 'var(--bg-hover)', padding: '0.25rem', borderRadius: '0.5rem', border: '1px solid var(--border-color)' }}>
                                <Calendar size={16} style={{ color: 'var(--text-secondary)', marginLeft: '0.5rem' }} />
                                <input 
                                    type="date" 
                                    value={startDate}
                                    onChange={(e) => setStartDate(e.target.value)}
                                    style={{ background: 'transparent', border: 'none', color: 'var(--text-primary)', padding: '0.25rem' }}
                                />
                                <span style={{ color: 'var(--text-secondary)' }}>to</span>
                                <input 
                                    type="date" 
                                    value={endDate}
                                    onChange={(e) => setEndDate(e.target.value)}
                                    style={{ background: 'transparent', border: 'none', color: 'var(--text-primary)', padding: '0.25rem' }}
                                />
                            </div>
                            <Button onClick={downloadCSV} variant="secondary" disabled={enquiries.length === 0}>
                                <Download size={16} /> Export (CSV)
                            </Button>
                        </div>
                    </div>

                    <div style={{ overflowX: 'auto' }}>
                        <table className="data-table" style={{ width: '100%', borderCollapse: 'collapse', textAlign: 'left' }}>
                            <thead>
                                <tr style={{ borderBottom: '1px solid var(--border-color)' }}>
                                    <th style={{ padding: '0.5rem', color: 'var(--text-secondary)', fontWeight: '500', width: '50px' }}>S.NO</th>
                                    <th style={{ padding: '0.5rem', color: 'var(--text-secondary)', fontWeight: '500' }}>Date & Time</th>
                                    <th style={{ padding: '0.5rem', color: 'var(--text-secondary)', fontWeight: '500' }}>Name</th>
                                    <th style={{ padding: '0.5rem', color: 'var(--text-secondary)', fontWeight: '500' }}>Phone</th>
                                    <th style={{ padding: '0.5rem', color: 'var(--text-secondary)', fontWeight: '500' }}>Design Code</th>
                                    <th style={{ padding: '0.5rem', color: 'var(--text-secondary)', fontWeight: '500' }}>Qty</th>
                                    <th style={{ padding: '0.5rem', color: 'var(--text-secondary)', fontWeight: '500' }}>Status</th>
                                    <th style={{ padding: '0.5rem', color: 'var(--text-secondary)', fontWeight: '500', textAlign: 'right' }}>Actions</th>
                                </tr>
                            </thead>
                            <tbody>
                                {loading ? (
                                    <tr>
                                        <td colSpan="8" style={{ textAlign: 'center', padding: '2rem', color: 'var(--text-secondary)' }}>Loading...</td>
                                    </tr>
                                ) : enquiries.length === 0 ? (
                                    <tr>
                                        <td colSpan="8" style={{ textAlign: 'center', padding: '2rem', color: 'var(--text-secondary)' }}>No enquiries found.</td>
                                    </tr>
                                ) : (
                                    enquiries.map((item, index) => (
                                        <tr key={item.id} style={{ borderBottom: '1px solid var(--border-color)' }}>
                                            <td style={{ padding: '0.5rem', color: 'var(--text-secondary)', fontSize: '0.875rem' }}>{index + 1}</td>
                                            <td style={{ padding: '0.5rem', color: 'var(--text-secondary)', fontSize: '0.875rem' }}>
                                                <div>{new Date(item.created_at).toLocaleDateString()}</div>
                                                <div style={{ fontSize: '0.75rem', opacity: 0.8 }}>{new Date(item.created_at).toLocaleTimeString()}</div>
                                            </td>
                                            <td style={{ padding: '0.5rem', fontWeight: '500', color: 'var(--text-primary)' }}>{item.name || '-'}</td>
                                            <td style={{ padding: '0.5rem', color: 'var(--text-primary)' }}>{item.phone_number}</td>
                                            <td style={{ padding: '0.5rem', color: 'var(--text-primary)', fontWeight: '500' }}>{item.design_code}</td>
                                            <td style={{ padding: '0.5rem' }}>
                                                <span style={{ background: 'var(--bg-hover)', color: 'var(--text-primary)', padding: '0.25rem 0.5rem', borderRadius: '1rem', fontSize: '0.875rem' }}>
                                                    {item.quantity}
                                                </span>
                                            </td>
                                            <td style={{ padding: '0.5rem' }}>
                                                <select 
                                                    value={item.status} 
                                                    onChange={(e) => handleStatusChange(item.id, e.target.value)}
                                                    style={{ 
                                                        padding: '0.25rem 0.5rem', 
                                                        borderRadius: '0.25rem', 
                                                        border: `1px solid ${getStatusColor(item.status)}`,
                                                        background: 'transparent',
                                                        color: getStatusColor(item.status),
                                                        fontWeight: '500',
                                                        fontSize: '0.875rem',
                                                        cursor: 'pointer'
                                                    }}
                                                >
                                                    <option value="Pending">Pending</option>
                                                    <option value="Processing">Processing</option>
                                                    <option value="Resolved">Resolved</option>
                                                </select>
                                            </td>
                                            <td style={{ padding: '0.5rem', textAlign: 'right' }}>
                                                <Button onClick={() => handleDelete(item.id)} variant="ghost" className="danger" size="icon" title="Delete Enquiry">
                                                    <Trash2 size={18} />
                                                </Button>
                                            </td>
                                        </tr>
                                    ))
                                )}
                            </tbody>
                        </table>
                    </div>
                    
                    {/* Pagination Controls */}
                    <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginTop: '1rem', padding: '1rem 0' }}>
                        <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', color: 'var(--text-secondary)' }}>
                            <span style={{ fontSize: '0.875rem' }}>Rows per page:</span>
                            <select 
                                value={limit} 
                                onChange={(e) => { setLimit(Number(e.target.value)); setPage(1); }}
                                style={{ padding: '0.25rem', borderRadius: '0.25rem', border: '1px solid var(--border-color)', background: 'var(--bg-hover)', color: 'var(--text-primary)', fontSize: '0.875rem' }}
                            >
                                <option value="10">10</option>
                                <option value="25">25</option>
                                <option value="50">50</option>
                                <option value="100">100</option>
                            </select>
                        </div>
                        
                        <div style={{ display: 'flex', alignItems: 'center', gap: '1rem', color: 'var(--text-secondary)' }}>
                            <span style={{ fontSize: '0.875rem' }}>
                                {totalCount === 0 ? '0' : `${(page - 1) * limit + 1}-${Math.min(page * limit, totalCount)}`} of {totalCount}
                            </span>
                            <div style={{ display: 'flex', gap: '0.25rem' }}>
                                <Button 
                                    variant="secondary" 
                                    style={{ padding: '0.25rem 0.5rem', height: 'auto', minHeight: 'auto' }}
                                    onClick={() => setPage(p => Math.max(1, p - 1))} 
                                    disabled={page === 1}
                                >
                                    Prev
                                </Button>
                                <Button 
                                    variant="secondary" 
                                    style={{ padding: '0.25rem 0.5rem', height: 'auto', minHeight: 'auto' }}
                                    onClick={() => setPage(p => p + 1)} 
                                    disabled={page * limit >= totalCount}
                                >
                                    Next
                                </Button>
                            </div>
                        </div>
                    </div>
                </section>
            </div>
        </AdminLayout>
    );
};

export default Enquiries;
